---
- hosts:
    - localhost
  tasks:
    - name: Install Required Packages
      become: yes
      apt:
        pkg:
          - bat
          - exa
          - git
          - fish
          - tmux
          - vim-nox
          - curl
          - silversearcher-ag
          - fzf
          - mgitstatus
          - python3-pip
          - python3-venv
          - libreadline-dev
          - libsqlite3-dev
          - libbz2-dev
          - libffi-dev
          - tig
          - tldr
          - fd-find
          - ripgrep
          - duf
          - aiksaurus
