---
- hosts:
  - localhost
  tasks:
  - name: Install Required Packages
    become: yes
    apt:
      pkg:
        - git
        - tmux
        - vim-nox
        - neovim
        - curl
        - silversearcher-ag
        - fzf
        - python3-pip
        - python3-venv
